{% set name = "types-pywin32" %}
{% set version = "306.0.0.20240312" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b0f3925e1600f28d58d8ed50f2e2edd3ef8d546d95214e178d8f553fae7e500b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8

test:
  commands:
    - pip check
    - test -f $SP_DIR/win32-stubs/__init__.pyi  # [unix]
    - if not exist %SP_DIR%\\win32-stubs\\__init__.pyi exit 1  # [win]
  requires:
    - pip

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for pywin32
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://github.com/python/typeshed
  dev_url: https://github.com/python/typeshed/tree/main/stubs/pywin32

extra:
  recipe-maintainers:
    - sobolevn
    - Ubadub
