{% set name = "types-pywin32" %}
{% set version = "306.0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8034b54d8a04664e8fc1f075a6f2dee1fd2f63d0091a228a44501c92a8e06353

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  commands:
    - pip check
    - test -f $SP_DIR/win32-stubs/__init__.pyi  # [unix]
    - if not exist %SP_DIR%\\win32-stubs\\__init__.pyi exit 1  # [win]
  requires:
    - pip

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for pywin32
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://github.com/python/typeshed
  dev_url: https://github.com/python/typeshed/tree/main/stubs/pywin32

extra:
  recipe-maintainers:
    - Ubadub
